version: '2'

services:
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            - "MINIO_ACCESS_KEY=SCALEWAYS3LIKE"
            - "MINIO_SECRET_KEY=424242424242"
        command: server /images

    web:
        depends_on:
            - "minio"
        build: ./api
        ports:
            - "5000:5000"
        volumes:
            - ".:/code"
